[package]
name = "sec2-using-trait-objects-that-allows-values-of-different-types"
version = "0.1.0"
authors = ["Shintaro Ikeda <ikenshirogivenup98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
